language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email:
    on_failure: always
node_js:
  - "10.16.0"
script:
  - npm run build
  - npm run lint
  - npm test
after_success:
  - npx codecov
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
