language: node_js
sudo: false
cache:
  directories:
    - $HOME/.npm
notifications:
  email: false
node_js:
  - 10.11
before_script:
  - export TZ=America/Bogota
script:
  - npm test
  - npx codecov
after_success:
  - npx semantic-release
