language: node_js
sudo: false
cache:
  directories:
    - $HOME/.npm
notifications:
  email:
    on_failure: always
node_js:
  - "10"
  - "8"
  - "6"
before_script:
  - export TZ=America/Bogota
script:
  - npm run build:dist
  - npm run build:docs
  - npm run lint
  - npm test
  - npx codecov
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - npm run deploy
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
