language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email:
    on_failure: always
node_js:
  - "8.10"
script:
  - npm run build:dist
  - npm run build:docs
  - npm run lint
  - npm test
after_success:
  - npx codecov
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
