name: Build and release
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-and-release:
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    uses: MauricioRobayo/workflows/.github/workflows/build-and-release.yml@main
